/**
 * PDF Report Generator for MathHero
 * @module utils/reportGenerator
 */

/**
 * Generate a practice report PDF
 * @param {Object} options - Report options
 * @param {string} options.username - User's name
 * @param {string} options.gender - User's gender (prince/princess)
 * @param {Object} options.stats - User's statistics
 * @param {Object} options.progress - User's progress data
 * @param {Object} options.t - Translation object
 * @returns {Promise<void>}
 */
export async function generateReport({ username, gender, stats, progress, t }) {
  // Dynamically import jspdf to reduce initial bundle size
  const { jsPDF } = await import('jspdf')

  const doc = new jsPDF()
  const pageWidth = doc.internal.pageSize.getWidth()

  // Colors based on gender
  const primaryColor = gender === 'prince' ? [74, 144, 217] : [255, 105, 180]
  const secondaryColor = gender === 'prince' ? [135, 206, 235] : [255, 182, 193]

  // Title
  doc.setFillColor(...primaryColor)
  doc.rect(0, 0, pageWidth, 40, 'F')

  doc.setTextColor(255, 255, 255)
  doc.setFontSize(24)
  doc.setFont('helvetica', 'bold')
  doc.text('MathHero Practice Report', pageWidth / 2, 20, { align: 'center' })

  doc.setFontSize(14)
  doc.text(username || (gender === 'prince' ? 'Little Prince' : 'Little Princess'), pageWidth / 2, 32, { align: 'center' })

  // Date
  doc.setTextColor(100, 100, 100)
  doc.setFontSize(10)
  doc.setFont('helvetica', 'normal')
  const today = new Date().toLocaleDateString()
  doc.text(`Generated: ${today}`, pageWidth / 2, 50, { align: 'center' })

  // Summary Section
  let yPos = 65

  doc.setFillColor(...secondaryColor)
  doc.roundedRect(15, yPos, pageWidth - 30, 45, 5, 5, 'F')

  doc.setTextColor(50, 50, 50)
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text('Summary', 25, yPos + 12)

  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')

  const summaryData = [
    [`Total Questions: ${stats.totalQuestions || 0}`, `Overall Accuracy: ${stats.overallAccuracy || 0}%`],
    [`Streak Days: ${stats.streakDays || 0}`, `Practice Sessions: ${Object.values(stats.operationStats || {}).reduce((sum, op) => sum + (op.sessions || 0), 0)}`]
  ]

  let summaryY = yPos + 25
  summaryData.forEach(row => {
    doc.text(row[0], 25, summaryY)
    doc.text(row[1], pageWidth / 2 + 10, summaryY)
    summaryY += 10
  })

  // Operations Progress
  yPos = 120

  doc.setTextColor(...primaryColor)
  doc.setFontSize(16)
  doc.setFont('helvetica', 'bold')
  doc.text('Progress by Operation', 15, yPos)

  yPos += 10

  const operations = ['addition', 'subtraction', 'multiplication', 'division', 'fraction']
  const operationNames = {
    addition: 'Addition (+)',
    subtraction: 'Subtraction (-)',
    multiplication: 'Multiplication (x)',
    division: 'Division (/)',
    fraction: 'Fractions'
  }

  operations.forEach((op, index) => {
    const opStats = stats.operationStats?.[op] || {}
    const opProgress = progress[op] || { completedLevels: [], unlockedLevel: 1 }

    const cardY = yPos + index * 25
    doc.setFillColor(245, 245, 245)
    doc.roundedRect(15, cardY, pageWidth - 30, 22, 3, 3, 'F')

    // Operation name
    doc.setTextColor(50, 50, 50)
    doc.setFontSize(11)
    doc.setFont('helvetica', 'bold')
    doc.text(operationNames[op], 20, cardY + 10)

    // Stats
    doc.setFont('helvetica', 'normal')
    doc.setFontSize(9)
    const levelText = `Levels: ${opProgress.completedLevels?.length || 0}/6`
    const questionsText = `Questions: ${opStats.questions || 0}`
    const accuracyText = `Accuracy: ${opStats.accuracy || 0}%`

    doc.text(levelText, 90, cardY + 10)
    doc.text(questionsText, 130, cardY + 10)
    doc.text(accuracyText, 175, cardY + 10)

    // Progress bar
    const barX = 20
    const barY = cardY + 14
    const barWidth = pageWidth - 50
    const barHeight = 4
    const progressPercent = ((opProgress.completedLevels?.length || 0) / 6) * 100

    doc.setFillColor(220, 220, 220)
    doc.roundedRect(barX, barY, barWidth, barHeight, 2, 2, 'F')

    if (progressPercent > 0) {
      doc.setFillColor(...primaryColor)
      doc.roundedRect(barX, barY, barWidth * (progressPercent / 100), barHeight, 2, 2, 'F')
    }
  })

  // Footer
  doc.setTextColor(150, 150, 150)
  doc.setFontSize(8)
  doc.text('Generated by MathHero - Math Practice for Kids', pageWidth / 2, 285, { align: 'center' })
  doc.text('https://github.com/hyu-im/MathHero', pageWidth / 2, 290, { align: 'center' })

  // Save the PDF
  const fileName = `MathHero_Report_${username || 'User'}_${today.replace(/\//g, '-')}.pdf`
  doc.save(fileName)
}

/**
 * Check if PDF generation is available
 * @returns {boolean}
 */
export function isPdfAvailable() {
  return typeof window !== 'undefined'
}
